[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:life_style_parsed_results]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work rabbitmq --queue=life_style_parsed_results --tries=3
autostart=true
autorestart=true
numprocs=4
redirect_stderr=true
stdout_logfile=/dev/stdout

[program:life_style_score_results]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work rabbitmq --queue=life_style_score_results --tries=3
autostart=true
autorestart=true
numprocs=4
redirect_stderr=true
stdout_logfile=/dev/stdout

[program:longevity_parsed_results]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work rabbitmq --queue=longevity_parsed_results --tries=3
autostart=true
autorestart=true
numprocs=4
redirect_stderr=true
stdout_logfile=/dev/stdout

[program:longevity_score_results]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work rabbitmq --queue=longevity_score_results --tries=3
autostart=true
autorestart=true
numprocs=4
redirect_stderr=true
stdout_logfile=/dev/stdout

[program:default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work rabbitmq --queue=default --tries=3
autostart=true
autorestart=true
numprocs=4
redirect_stderr=true
stdout_logfile=/dev/stdout
